config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'log_out', to: 'sessions#destroy', as: 'log_out'
  resources :sessions, only: %i[create destroy]

  get 'user_answers/submit', to: 'user_answers#submit'
  get 'user_answers/results', to: 'user_answers#results'
  resources :user_answers, only: %i[new create edit update index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/examination.rb
class Examination < ApplicationRecord
  has_many :user_answers

  # 使用可能な全問題数を取得
  scope :get_examination_count, -> { where(can_use: true).pluck(:id).size }
  # 使用可能な全問題データのIDをランダムに取得
  scope :get_examination_ids_rand, -> (question_num_all) { where(can_use: true).order("RANDOM()").limit(question_num_all).pluck(:id) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_answers

  class << self
    def find_or_create_from_auth_hash(auth_hash)
      user_params = user_params_from_auth_hash(auth_hash)
      find_or_create_by(uid: user_params[:uid]) do |user|
        user.update(user_params)
      end
    end

    private

    def user_params_from_auth_hash(auth_hash)
      {
        name:  auth_hash.info.name,
        image: auth_hash.info.image,
        uid:   auth_hash.uid
      }
    end
  end
end

app/models/user_answer.rb
class UserAnswer < ApplicationRecord
  belongs_to :user
  belongs_to :examination
  delegate :question_txt, to: :examination, prefix: false

  # 指定したidのレコードを取得
  scope :get_by_id, ->(id) { find(id) }
  # ユーザーのquestion_numの最大値を取得
  scope :get_question_num_all, ->(id, num) { where(user_id: id).maximum(num) }
  # ユーザーのquestion_numが1以上のレコードの中で最小のidを取得
  scope :get_id_first, ->(id) { where(user_id: id, question_num: 1..).minimum(:id) }

  # 提出前の回答欄レコードを確認して、回答欄レコードが存在しない場合は作成
  def self.review_and_create(user_id, question_num_all)
    # 受験回数、ただし初回受験時ならばnilなので0を返す
    attempts_num = where(user_id: user_id).maximum(:attempts_num) || 0

    # 初回受験時は回答欄レコードを作成
    return create_user_answers(user_id, question_num_all, attempts_num) if attempts_num == 0

    # 二度目の受験以降は未回答の回答欄レコードが存在するか確認
    user_answers = where(user_id: user_id, question_num: 1..).order(:question_num)
    # 未回答の回答欄レコードが存在する場合はそのまま遷移
    if user_answers.present?
      return true, user_answers.first.id, nil
    else
      # 回答欄レコードを作成
      return create_user_answers(user_id, question_num_all, attempts_num)
    end
  end

  # 合否判定して、正解数と合否結果と保存の成否を返す
  def self.results(id)
    user_answers = includes(:examination).where(user_id: id, question_num: 1..).order(:question_num)

    correct_num = 0
    user_answers.each do |ua|
      if ua.choiced_ans == ua.examination.correct_ans
        ua.cleared = true
        correct_num += 1
      else
        ua.cleared = false
      end

      ua.question_num = 0
      return 0, false, false if !ua.save
    end

    if user_answers.size > 0 && Float(user_answers.size * ENV['PASSING_SCORE_THRESHOLD'].to_f / 100) <= Float(correct_num)
      passed = true
      User.find(id).increment!(:passed_num)
    else
      passed = false
    end

    return correct_num, passed, true
  end

  # 現在のユーザーと回答者が異なるかを判定
  def belongs_to_user?(user_id)
    self.user_id == user_id
  end

  # 選択されている回答をフラグに変換
  def get_choiced_ans_flags
    @choiced_ans_yes = self.choiced_ans == 'yes'
    @choiced_ans_no = self.choiced_ans == 'no'
    return @choiced_ans_yes, @choiced_ans_no
  end

  # 最大すなわち、最終問題かを判定
  def is_last_question?(user_id)
    self.question_num == UserAnswer.get_question_num_all(user_id, :question_num)
  end

  # 回答した選択肢の更新
  def update_choiced_ans(params)
    self.choiced_ans = params[:choiced_ans]
    begin
      self.save!
      return true, nil
    rescue ActiveRecord::RecordInvalid => e
      return false, e.record.errors.full_messages
    end
  end

  private

  def self.create_user_answers(user_id, question_num_all, attempts_num)
    # 使用可能な問題のIDをランダムにquestion_num_all個取得
    examination_ids_rand = Examination.get_examination_ids_rand(question_num_all)

    # 回答欄レコードを作成
    user_answers = []
    examination_ids_rand.size.times do |i|
      user_answer = UserAnswer.new
      user_answer.user_id = user_id
      user_answer.examination_id = examination_ids_rand[i]
      user_answer.attempts_num = attempts_num + 1
      user_answer.question_num = i + 1
      user_answers << user_answer
    end

    # 回答欄レコードを保存
    begin
      return true, user_answers.first.id, nil if user_answers.all?(&:save!)
    rescue ActiveRecord::RecordInvalid => e
      return false, nil, e.record.errors.full_messages
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :check_logged_in
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def check_logged_in
    return if current_user
    flash[:error] = 'ログインしてください'
    redirect_to root_path
  end

  private

  def record_not_found
    render plain: "404 Not Found", status: 404
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :check_logged_in, only: :index

  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :check_logged_in, only: :create

  def create
    if (user = User.find_or_create_from_auth_hash(auth_hash))
      log_in user
    end
    flash[:notice] = 'ログインしました。'
    redirect_to root_path
  end

  def destroy
    log_out
    flash[:notice] = 'ログアウトしました。'
    redirect_to root_path
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/user_answers_controller.rb
class UserAnswersController < ApplicationController
  before_action :set_no_cache

  # 回答欄テーブルのデータ作成準備
  def new
    # 試験問題テーブルの使用可能な全問題数を取得
    @examination_count = Examination.get_examination_count
  end

  # 回答欄テーブルのデータ作成とレコード保存
  def create
    # セッションユーザーのID
    user_id = session[:user_id]
    user_answer_params = params.permit(:question_num_all)

    # 提出前のレコードの確認と作成
    is_saved, id, flash_messages = UserAnswer.review_and_create(user_id, user_answer_params[:question_num_all].to_i)

    # 保存の成否を確認
    if is_saved
      # 通知
      flash[:notice] << flash_messages if flash_messages.present?
      # 選択肢提示画面へリダイレクト
      redirect_to edit_user_answer_path(id)
    else
      # 通知
      flash.now[:error] << flash_messages if flash_messages.present?
      # 開始確認画面へ戻す
      render :new
    end
  end

  # 回答欄テーブルのchoiced_ansカラムの更新準備
  def edit
    @user_answer = UserAnswer.get_by_id(params[:id])

    if @user_answer.nil? || !@user_answer.belongs_to_user?(session[:user_id])
      # セッションユーザーと回答者が異なる場合、トップページへリダイレクト
      flash.now[:error] = '他のユーザーの回答は編集できません。'
      redirect_to root_path
    else
      # すでに回答している問題の場合、その選択肢を選択済みにする
      @choiced_ans_yes, @choiced_ans_no = @user_answer.get_choiced_ans_flags
    end
  end

  # 回答欄テーブルのchoiced_ansカラムの更新
  def update
    @user_answer = UserAnswer.get_by_id(params[:id])
    if params[:user_answer].nil?
      flash.now[:error] = '「はい」か「いいえ」のどちらかを選択してください。'
      # 同じ問題番号の画面を再表示
      render :edit
      return
    end

    is_saved, e_messages = @user_answer.update_choiced_ans(params[:user_answer])

    # 保存の成否を確認
    if is_saved
      # 最終問題かを確認
      if @user_answer.is_last_question?(session[:user_id])
        flash[:notice] = '回答が完了したら提出してください。または、第1問目から選択しなおすこともできます。'
        # 提出確認画面へ
        redirect_to user_answers_submit_path
      else
        # 最終問題でなければ次の問題へ
        redirect_to edit_user_answer_path(@user_answer.id + 1)
      end
    else
      # 通知
      flash.now[:error] << e_messages
      # 同じ問題番号の画面を再表示
      render :edit
    end
  end

  # ここで答案を提出するか確認
  def submit
    # 問題の先頭番号を取得
    @id_first = UserAnswer.get_id_first(session[:user_id])
    # user_answers_results_pathから戻るボタン等で戻った時のエラー処理が必要
  end

  # ここで合否判定を行う
  def results
    @correct_num, @passed, is_saved = UserAnswer.results(session[:user_id])
    render :submit unless is_saved  # 保存に失敗してたら、提出画面を再表示
  end

  # 回答欄テーブルのレコード一覧を表示（予定）
  def index
  end

  private

  def set_no_cache
    response.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    return unless (user_id = session[:user_id])

    @current_user ||= User.find_by(id: user_id)
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/user_answer_helper.rb
module UserAnswerHelper
  # 全問題数を設定
  def question_num_all
    return ENV['QUESTION_NUM_ALL'].to_i
  end

  # 合格の最低点数を設定
  def passing_score_threshold
    return (question_num_all * ENV['PASSING_SCORE_THRESHOLD'].to_f / 100).ceil
  end
end

app/views/home/index.html.erb
<!-- 機能表示 -->
<section class="bg-body-tertiary" id="home">
  <div class="container text-center pb-3">
    <div class="row pt-3 mt-2 mb-3">
      <div class="col">
        <h1>今後ほかの機能も追加予定です</h1>
      </div>
    </div>

    <div class="row g-4">
      <!-- D&D第5版PL -->
      <div class="col-md-4">
        <div class="border p-3 shadow">
          <i class="bi bi-dice-1 text-info fs-1"></i>
          <h5>D&D第5版PL試験</h5>
          <p class="text-body-secondary">D&Dのプレイヤーとしての知識を試す試験です。</p>
          <%= link_to "詳細はこちら",  { controller: 'user_answers', action: 'new' }, class: 'btn btn-info rounded-pill text-white' %>
        </div>
      </div>

      <!-- 未定 -->
      <div class="col-md-4">
        <div class="border p-3 shadow">
          <i class="bi bi-dice-2 text-info fs-1"></i>
          <h5>過去問の確認</h5>
          <p class="text-body-secondary">過去の試験結果を確認できる予定です。</p>
          <%= link_to "未定",  { controller: 'user_answers', action: 'index' }, class: 'btn btn-info rounded-pill text-white' %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DnD5e向上委員会</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <!-- Bootstrap -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />
    <!-- Bootstrap Icons -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
    />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  </head>

  <body class="">
    <!-- ナビゲーションバー -->
    <nav
      class="navbar navbar-expand-lg bg-secondary fixed-top"
      data-bs-theme="dark"
      id="navbar"
    >
      <!-- ブランド -->
      <div class="ms-2 me-auto">
        <a class="navbar-brand" href="/">
          <i class="bi bi-magic text-danger"></i> DnD5e向上委員会
        </a>
      </div>

      <!-- トグルボタン -->
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNav"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- リンク一覧 -->
      <div class="collapse navbar-collapse ms-5" id="navbarNav">
        <!-- テキストの折り返し対策のため、スタイルを追加 -->
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <%= link_to 'ホーム', root_path, class: current_page?(root_path) ? 'nav-link active' : 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to '試験', new_user_answer_path, class: current_page?(new_user_answer_path) ? 'nav-link active' : 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to '過去問', user_answers_path, class: current_page?(user_answers_path) ? 'nav-link active' : 'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>

    <!-- ヘッダー -->
    <header class="bg-body-tertiary mt-5 pt-3">
    <% if flash.any? %>
      <% flash.each do |type, message| %>
        <% if type == 'notice' %>
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            <%= message %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% elsif type == 'error' %>
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <%= message %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% else %>
          <div class="alert alert-<%= type %> alert-dismissible fade show" role="alert">
            <%= message %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
      <% end %>
    <% end %>
    </header>

    <%= yield %>

    <!-- フッター -->
    <footer class="mt-auto py-2 bg-secondary text-white">
      <div class="container text-center">
        <% if current_user %>  <!-- ログインしていれば、ユーザーの情報を表示 -->
          <%= image_tag current_user.image, width: "20px" %>
          <%= current_user.name %>さん
          <%= link_to raw('<i class="bi bi-door-closed"></i> ログアウト'), log_out_path, class: "text-warning" %>
        <% else %>  <!--ログインしていなければ、ログインボタンを表示-->
          <%= button_to raw('<i class="bi bi-discord"></i> Discordでログイン'), "/auth/discord", method: :post, class: "btn btn-info text-white" %>
        <% end %>
      </div>
      <div class="container text-center">
        &copy;2024 DnD5e向上委員会
        <!-- ログインしてるユーザーが管理者の場合のみ -->
        <% if current_user.try(:admin?) %>
          <%= link_to '管理者ログイン', rails_admin_path, class: "text-danger" %>
        <% end %>
      </div>
    </footer>

    <!-- Bootstrap -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

app/views/user_answers/create.html.erb
<h1>UserAnswers#create</h1>
<p>Find me in app/views/user_answers/create.html.erb</p>

app/views/user_answers/edit.html.erb
<!-- 問題 -->
<section class="py-5 bg-body-tertiary" id="">
  <div class="container text-center pb-3">
    <!-- 何問目か表示 -->
    <h1 class="pb-3"><%= "第#{@user_answer.question_num}問目" %></h1>

    <!-- 文章 -->
    <div class="row pb-3 text-start">
      <div class="col">
        <h4><%= @user_answer.question_txt %></h4>
      </div>
    </div>

    <!-- 回答 -->
    <div class="row">
      <%= form_with(model: @user_answer, url: user_answer_path(@user_answer), method: :patch, local: true) do |form| %>
        <div class="d-flex align-items-center justify-content-center">
          <div class="me-4 w-100">
            <%= form.radio_button :choiced_ans, 'yes', class: 'd-none', id: 'radio_yes', checked: @choiced_ans_yes %>
            <%= label_tag :radio_yes, 'はい', class: 'btn btn-outline-primary btn-lg w-100' %>
          </div>
          <div class="ms-4 w-100">
            <%= form.radio_button :choiced_ans, 'no', class: 'd-none', id: 'radio_no', checked: @choiced_ans_no %>
            <%= label_tag :radio_no, 'いいえ', class: 'btn btn-outline-primary btn-lg w-100' %>
          </div>
        </div>
        <div class="d-grid gap-2 mx-auto">
          <%= form.submit '次へ進む', class: 'btn btn-danger mt-5' %>
        </div>
      <% end %>
    </div>
  </div>
</section>

<!-- このスクリプトは、user_answers/edit.html.erbでのみ読み込むこと -->
<script>
  $(document).ready(function() {
    const radioYes = $('#radio_yes');
    const radioNo = $('#radio_no');
    const labelYes = $('label[for="radio_yes"]');
    const labelNo = $('label[for="radio_no"]');

    // 初期状態の設定
    if (radioYes.prop('checked')) {
      labelYes.removeClass('btn-outline-primary');
      labelYes.addClass('btn-primary');
    } else if (radioNo.prop('checked')) {
      labelNo.removeClass('btn-outline-primary');
      labelNo.addClass('btn-primary');
    }

    // ラジオボタンyesがクリックされた時の処理
    radioYes.on('click', function() {
      labelYes.removeClass('btn-outline-primary');
      labelYes.addClass('btn-primary');
      labelNo.removeClass('btn-primary');
      labelNo.addClass('btn-outline-primary');
    });

    // ラジオボタンnoがクリックされた時の処理
    radioNo.on('click', function() {
      labelNo.removeClass('btn-outline-primary');
      labelNo.addClass('btn-primary');
      labelYes.removeClass('btn-primary');
      labelYes.addClass('btn-outline-primary');
    });
  });
  </script>

app/views/user_answers/index.html.erb
<section class="py-5 bg-body-tertiary" id="">
  <div class="container text-center pb-1">
    <div class="row">
      <div class="col">
          <h1>かべのなかにいる</h1>
          <p>＼きゅりおしてぃ きるど ざ きゃっと。／</p>
      </div>
    </div>
  </div>
</section>

app/views/user_answers/new.html.erb
<!-- D&D第5版PL検定 -->
<section class="py-5 bg-body-tertiary" id="">
  <div class="container text-center pb-3">
    <div class="row">
      <div class="col">
        <h2 class="mb-3">D&D第5版PL試験</h2>
        <p>
          プレイヤーとしてのルール理解度を確認するため、<br />
          「<%= link_to 'フィフスエディションRPG', 'https://wit-awscms-witweb.s3-ap-northeast-1.amazonaws.com/hjcardgamer/5eRPG_Core_20240315.pdf', target: '_blank' %>」のPDFファイルをもとに、<br />
          「はい」or「いいえ」で回答できる問題を用意しました。
        </p>
        <p>
          現在のところ、問題数は全<%= @examination_count %>問です。<br />
          その中から<%= question_num_all %>問がランダムに出題されます。<br />
          <%= passing_score_threshold %>問以上の正解で合格です。
        </p>
        <div class="d-grid gap-2 mx-auto">
          <%= form_with(url: user_answers_path, method: :post, local: true) do |form| %>
            <%= form.hidden_field :question_num_all, value: @question_num_all %>
            <div class="d-grid gap-2 mx-auto">
              <%= form.submit 'スタート！', class: 'btn btn-danger mt-5' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/user_answers/results.html.erb
<!-- 結果発表 -->
<section class="py-5 bg-body-tertiary" id="">
  <div class="container text-center pb-3">
    <div class="row">
      <div class="col">
        <h2 class="mb-3">採点の結果…</h2>
        <p><%= current_user.name %>さんの正解数は<span class="text-danger fw-bold"><%= @correct_num %></span>問です。</p>
        <p>
        <% if @passed %>
          おめでとうございます！合格です！！
        <% else %>
          残念ながら不合格です…
        <% end %>
        </p>
      </div>
    </div>
  </div>
</section>

app/views/user_answers/submit.html.erb
<!-- 提出確認 -->
<section class="py-5 bg-body-tertiary" id="">
  <div class="container text-center pb-3">
    <!-- 提出？ -->
    <h1 class="pb-3">答案を提出しますか？</h1>

    <div class="row">
      <div class="d-grid gap-2 mx-auto">
        <%= link_to "問題に戻る",  edit_user_answer_path(@id_first), class: 'btn btn-primary mt-5' %>
      </div>
    </div>

    <div class="row">
      <div class="d-grid gap-2 mx-auto">
        <%= link_to "答案を提出",  user_answers_results_path, class: 'btn btn-danger mt-5' %>
      </div>
    </div>
  </div>
</section>